### ISSUE TITLE
License

### ISSUE THREAD

**Issue by d6y** [tptodorov/aws-lambda-scalajs#1]
This is wonderful - you've figured out a bunch of things I was battling with. Thank you.

Can you add a license to make it easier for myself and others to use this?

**Comment by d6y** [comment]
Hello @tptodorov - could you consider adding a license file, or stating here on this issue what the license is for this work? Thank you.

**Comment by tptodorov** [comment]
added MIT license

**Comment by d6y** [comment]
Thank you!
